RANDOM_FOREST:
  n_estimators: 100
  max_depth: None
  min_samples_split: 5

GRADIENT_BOOSTING:
  learning_rate: 0.1
  n_estimators: 100
  max_depth: 5 

XGBoostRegressor:
  learning_rate: 0.1
  n_estimators: 100
  max_depth: 5

Hyperopt_params:
  n_estimators:
    - 10
    - 500
  max_depth:
    - 5
    - 20
  min_samples_split:
    - 0
    - 5 

select_model: 
  algo: XGBoostRegressor
  n_estimators: 500
  max_depth: 15
  min_samples_split: 0       # set 0 if not required 
  learning_rate: 0.1         # set 0 if not required