# RANDOM_FOREST:
#   n_estimators: 100
#   max_depth: None
#   min_samples_split: 5

# GRADIENT_BOOSTING:
#   learning_rate: 0.1
#   n_estimators: 100
#   max_depth: 5 

# XGBoostRegressor:
#   learning_rate: 0.1
#   n_estimators: 100
#   max_depth: 5

Hyperopt_params:
  XGBoostRegressor:
    n_estimators: [10,500]
    max_depth: [5,40]
    min_child_weight: [1,15]
    gamma: [0,5]
    learning_rate: [0.01,0.3]

  GRADIENT_BOOSTING:
    n_estimators: [10,500]
    max_depth: [5,40]
    learning_rate: [0.01,0.3]

  RANDOM_FOREST:
    n_estimators: [10,500]
    max_depth: [5,10]
    min_samples_split: [2,5]




select_model: 
  algo: XGBoostRegressor
  n_estimators: 200
  max_depth: 15
  min_samples_split: 0       # set 0 if not required 
  learning_rate: 0.1         # set 0 if not required